[package]
name = "rusty-rover"
version = "0.1.0"
authors = ["Mukund Bhudia <mukund_bhudia@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
